import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ClientComponent from "../../components/Client";
import { GoogleOAuthProvider } from "@react-oauth/google";

import Navbar from "../../components/Navbar";
import Sidebar from "../../components/Sidebar";
import Provider from "../../components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GoogleOAuthProvider
      clientId={`${process.env.NEXT_PUBLIC_GOOGLE_API_TOKEN}`}
    >
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <Navbar />

            <div className=" flex gap-6 md:gap-20">
              <div className=" h-[92vh] overflow-hidden xl:hover:overflow-auto ">
                <Sidebar />
              </div>

              <ClientComponent>{children}</ClientComponent>
            </div>
          </Provider>
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
